//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FI.WebAtividadeEntrevista.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FI.WebAtividadeEntrevista.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro parcialmente realizado..
        /// </summary>
        public static string Erro_Cadastro_Parcial {
            get {
                return ResourceManager.GetString("Erro_Cadastro_Parcial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF {0} do cliente {1} é inválido..
        /// </summary>
        public static string Erro_CPF_Beneficiario {
            get {
                return ResourceManager.GetString("Erro_CPF_Beneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite um CPF válido no formato XXX.XXX.XXX-XX.
        /// </summary>
        public static string Erro_CPF_Formato {
            get {
                return ResourceManager.GetString("Erro_CPF_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido. Por favor, verifique os dados e tente novamente..
        /// </summary>
        public static string Erro_CPF_Invalido {
            get {
                return ResourceManager.GetString("Erro_CPF_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF informado já pertence a um cliente. Insira um CPF válido..
        /// </summary>
        public static string Erro_CPF_Ja_Existe {
            get {
                return ResourceManager.GetString("Erro_CPF_Ja_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite um e-mail válido.
        /// </summary>
        public static string Erro_Email_Formato {
            get {
                return ResourceManager.GetString("Erro_Email_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um ou mais campos estão inválidos..
        /// </summary>
        public static string Erro_Modelo_Invalido {
            get {
                return ResourceManager.GetString("Erro_Modelo_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro alterado com sucesso..
        /// </summary>
        public static string Sucesso_Alteracao {
            get {
                return ResourceManager.GetString("Sucesso_Alteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro realizado..
        /// </summary>
        public static string Sucesso_Cadastro {
            get {
                return ResourceManager.GetString("Sucesso_Cadastro", resourceCulture);
            }
        }
    }
}
