CREATE OR ALTER PROC FI_SP_ConsCliente    
    @ID BIGINT = 0    
AS    
BEGIN    
    SELECT 
    C.ID,
    C.CEP,
    C.CIDADE,
    C.EMAIL,
    C.ESTADO,
    C.LOGRADOURO,
    C.NACIONALIDADE,
    C.NOME,
    C.SOBRENOME,
    C.TELEFONE,
    C.CPF AS Cpf,
    B.ID AS B_ID, 
    B.CPF AS B_CPF, 
    B.NOME AS B_NOME 
FROM CLIENTES AS C WITH (NOLOCK)
LEFT JOIN BENEFICIARIOS AS B WITH (NOLOCK) ON B.IDCLIENTE = C.ID
WHERE (@ID = 0 OR C.ID = @ID)
END